apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fe
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: frontend-key
      containers:
      - name: fe
        image: eu.gcr.io/college-de-france/fe
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        command: ["go-wrapper"]
        args: ["run", "--project_id=college-de-france", "--listen_addr=0.0.0.0:80", "--elastic_address=http://elasticsearch:9200"]
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fe-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: fe-static-ip
spec:
  backend:
    serviceName: fe
    servicePort: 80
